// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STEM_Shop.Data.Models;

public partial class Transaction
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public DateTime? TransactionDate { get; set; }

    public virtual Order Order { get; set; }
}